# Generated by Django 4.0.4 on 2022-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_rename_content_todotask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
